// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: heat_beat.proto
// Protobuf C++ Version: 6.31.1

#ifndef heat_5fbeat_2eproto_2epb_2eh
#define heat_5fbeat_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_heat_5fbeat_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_heat_5fbeat_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_heat_5fbeat_2eproto;
}  // extern "C"
namespace heartbeat {
enum Heartbeat_Status : int;
extern const uint32_t Heartbeat_Status_internal_data_[];
class ChunkMetadata;
struct ChunkMetadataDefaultTypeInternal;
extern ChunkMetadataDefaultTypeInternal _ChunkMetadata_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ChunkMetadata_class_data_;
class FileChunk;
struct FileChunkDefaultTypeInternal;
extern FileChunkDefaultTypeInternal _FileChunk_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FileChunk_class_data_;
class Heartbeat;
struct HeartbeatDefaultTypeInternal;
extern HeartbeatDefaultTypeInternal _Heartbeat_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Heartbeat_class_data_;
}  // namespace heartbeat
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::heartbeat::Heartbeat_Status_internal_data_>
    internal::EnumTraitsImpl::value<::heartbeat::Heartbeat_Status>;
}  // namespace protobuf
}  // namespace google

namespace heartbeat {
enum Heartbeat_Status : int {
  Heartbeat_Status_UNKNOWN = 0,
  Heartbeat_Status_ALIVE = 1,
  Heartbeat_Status_DEAD = 2,
  Heartbeat_Status_Heartbeat_Status_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Heartbeat_Status_Heartbeat_Status_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Heartbeat_Status_internal_data_[];
inline constexpr Heartbeat_Status Heartbeat_Status_Status_MIN =
    static_cast<Heartbeat_Status>(0);
inline constexpr Heartbeat_Status Heartbeat_Status_Status_MAX =
    static_cast<Heartbeat_Status>(2);
inline bool Heartbeat_Status_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int Heartbeat_Status_Status_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Heartbeat_Status_descriptor();
template <typename T>
const ::std::string& Heartbeat_Status_Name(T value) {
  static_assert(::std::is_same<T, Heartbeat_Status>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Status_Name().");
  return Heartbeat_Status_Name(static_cast<Heartbeat_Status>(value));
}
template <>
inline const ::std::string& Heartbeat_Status_Name(Heartbeat_Status value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Heartbeat_Status_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool Heartbeat_Status_Parse(
    ::absl::string_view name, Heartbeat_Status* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Heartbeat_Status>(Heartbeat_Status_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class Heartbeat final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:heartbeat.Heartbeat) */ {
 public:
  inline Heartbeat() : Heartbeat(nullptr) {}
  ~Heartbeat() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Heartbeat* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Heartbeat));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Heartbeat(::google::protobuf::internal::ConstantInitialized);

  inline Heartbeat(const Heartbeat& from) : Heartbeat(nullptr, from) {}
  inline Heartbeat(Heartbeat&& from) noexcept
      : Heartbeat(nullptr, ::std::move(from)) {}
  inline Heartbeat& operator=(const Heartbeat& from) {
    CopyFrom(from);
    return *this;
  }
  inline Heartbeat& operator=(Heartbeat&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Heartbeat& default_instance() {
    return *reinterpret_cast<const Heartbeat*>(
        &_Heartbeat_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Heartbeat& a, Heartbeat& b) { a.Swap(&b); }
  inline void Swap(Heartbeat* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Heartbeat* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Heartbeat* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Heartbeat>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Heartbeat& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Heartbeat& from) { Heartbeat::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Heartbeat* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "heartbeat.Heartbeat"; }

 protected:
  explicit Heartbeat(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Heartbeat(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Heartbeat& from);
  Heartbeat(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Heartbeat&& from) noexcept
      : Heartbeat(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Status = Heartbeat_Status;
  static constexpr Status UNKNOWN = Heartbeat_Status_UNKNOWN;
  static constexpr Status ALIVE = Heartbeat_Status_ALIVE;
  static constexpr Status DEAD = Heartbeat_Status_DEAD;
  static inline bool Status_IsValid(int value) {
    return Heartbeat_Status_IsValid(value);
  }
  static constexpr Status Status_MIN = Heartbeat_Status_Status_MIN;
  static constexpr Status Status_MAX = Heartbeat_Status_Status_MAX;
  static constexpr int Status_ARRAYSIZE = Heartbeat_Status_Status_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Status_descriptor() {
    return Heartbeat_Status_descriptor();
  }
  template <typename T>
  static inline const ::std::string& Status_Name(T value) {
    return Heartbeat_Status_Name(value);
  }
  static inline bool Status_Parse(
      ::absl::string_view name, Status* PROTOBUF_NONNULL value) {
    return Heartbeat_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kCpuFieldNumber = 1,
    kDiskFieldNumber = 2,
    kCountFieldNumber = 3,
    kStatusFieldNumber = 4,
  };
  // int32 cpu = 1;
  void clear_cpu() ;
  ::int32_t cpu() const;
  void set_cpu(::int32_t value);

  private:
  ::int32_t _internal_cpu() const;
  void _internal_set_cpu(::int32_t value);

  public:
  // int32 disk = 2;
  void clear_disk() ;
  ::int32_t disk() const;
  void set_disk(::int32_t value);

  private:
  ::int32_t _internal_disk() const;
  void _internal_set_disk(::int32_t value);

  public:
  // int32 count = 3;
  void clear_count() ;
  ::int32_t count() const;
  void set_count(::int32_t value);

  private:
  ::int32_t _internal_count() const;
  void _internal_set_count(::int32_t value);

  public:
  // .heartbeat.Heartbeat.Status status = 4;
  void clear_status() ;
  ::heartbeat::Heartbeat_Status status() const;
  void set_status(::heartbeat::Heartbeat_Status value);

  private:
  ::heartbeat::Heartbeat_Status _internal_status() const;
  void _internal_set_status(::heartbeat::Heartbeat_Status value);

  public:
  // @@protoc_insertion_point(class_scope:heartbeat.Heartbeat)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Heartbeat& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t cpu_;
    ::int32_t disk_;
    ::int32_t count_;
    int status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_heat_5fbeat_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Heartbeat_class_data_;
// -------------------------------------------------------------------

class FileChunk final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:heartbeat.FileChunk) */ {
 public:
  inline FileChunk() : FileChunk(nullptr) {}
  ~FileChunk() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FileChunk* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FileChunk));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FileChunk(::google::protobuf::internal::ConstantInitialized);

  inline FileChunk(const FileChunk& from) : FileChunk(nullptr, from) {}
  inline FileChunk(FileChunk&& from) noexcept
      : FileChunk(nullptr, ::std::move(from)) {}
  inline FileChunk& operator=(const FileChunk& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileChunk& operator=(FileChunk&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileChunk& default_instance() {
    return *reinterpret_cast<const FileChunk*>(
        &_FileChunk_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(FileChunk& a, FileChunk& b) { a.Swap(&b); }
  inline void Swap(FileChunk* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileChunk* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileChunk* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FileChunk>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FileChunk& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FileChunk& from) { FileChunk::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FileChunk* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "heartbeat.FileChunk"; }

 protected:
  explicit FileChunk(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FileChunk(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FileChunk& from);
  FileChunk(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FileChunk&& from) noexcept
      : FileChunk(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kChunkIdFieldNumber = 1,
    kDataFieldNumber = 2,
  };
  // string chunk_id = 1;
  void clear_chunk_id() ;
  const ::std::string& chunk_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_chunk_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_chunk_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_chunk_id();
  void set_allocated_chunk_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_chunk_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_chunk_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_chunk_id();

  public:
  // bytes data = 2;
  void clear_data() ;
  const ::std::string& data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_data();
  void set_allocated_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // @@protoc_insertion_point(class_scope:heartbeat.FileChunk)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 36,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FileChunk& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr chunk_id_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_heat_5fbeat_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull FileChunk_class_data_;
// -------------------------------------------------------------------

class ChunkMetadata final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:heartbeat.ChunkMetadata) */ {
 public:
  inline ChunkMetadata() : ChunkMetadata(nullptr) {}
  ~ChunkMetadata() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ChunkMetadata* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ChunkMetadata));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ChunkMetadata(::google::protobuf::internal::ConstantInitialized);

  inline ChunkMetadata(const ChunkMetadata& from) : ChunkMetadata(nullptr, from) {}
  inline ChunkMetadata(ChunkMetadata&& from) noexcept
      : ChunkMetadata(nullptr, ::std::move(from)) {}
  inline ChunkMetadata& operator=(const ChunkMetadata& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChunkMetadata& operator=(ChunkMetadata&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ChunkMetadata& default_instance() {
    return *reinterpret_cast<const ChunkMetadata*>(
        &_ChunkMetadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ChunkMetadata& a, ChunkMetadata& b) { a.Swap(&b); }
  inline void Swap(ChunkMetadata* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChunkMetadata* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ChunkMetadata* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ChunkMetadata>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ChunkMetadata& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ChunkMetadata& from) { ChunkMetadata::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ChunkMetadata* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "heartbeat.ChunkMetadata"; }

 protected:
  explicit ChunkMetadata(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ChunkMetadata(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ChunkMetadata& from);
  ChunkMetadata(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ChunkMetadata&& from) noexcept
      : ChunkMetadata(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kReplicaServersFieldNumber = 4,
    kChunkIdFieldNumber = 1,
    kHashFieldNumber = 3,
    kSizeFieldNumber = 2,
  };
  // repeated string replica_servers = 4;
  int replica_servers_size() const;
  private:
  int _internal_replica_servers_size() const;

  public:
  void clear_replica_servers() ;
  const ::std::string& replica_servers(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_replica_servers(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_replica_servers(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_replica_servers();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_replica_servers(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& replica_servers() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_replica_servers();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_replica_servers() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_replica_servers();

  public:
  // string chunk_id = 1;
  void clear_chunk_id() ;
  const ::std::string& chunk_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_chunk_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_chunk_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_chunk_id();
  void set_allocated_chunk_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_chunk_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_chunk_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_chunk_id();

  public:
  // string hash = 3;
  void clear_hash() ;
  const ::std::string& hash() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_hash(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_hash();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_hash();
  void set_allocated_hash(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_hash() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_hash(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_hash();

  public:
  // int64 size = 2;
  void clear_size() ;
  ::int64_t size() const;
  void set_size(::int64_t value);

  private:
  ::int64_t _internal_size() const;
  void _internal_set_size(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:heartbeat.ChunkMetadata)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 59,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ChunkMetadata& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> replica_servers_;
    ::google::protobuf::internal::ArenaStringPtr chunk_id_;
    ::google::protobuf::internal::ArenaStringPtr hash_;
    ::int64_t size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_heat_5fbeat_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ChunkMetadata_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Heartbeat

// int32 cpu = 1;
inline void Heartbeat::clear_cpu() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cpu_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t Heartbeat::cpu() const {
  // @@protoc_insertion_point(field_get:heartbeat.Heartbeat.cpu)
  return _internal_cpu();
}
inline void Heartbeat::set_cpu(::int32_t value) {
  _internal_set_cpu(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:heartbeat.Heartbeat.cpu)
}
inline ::int32_t Heartbeat::_internal_cpu() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cpu_;
}
inline void Heartbeat::_internal_set_cpu(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cpu_ = value;
}

// int32 disk = 2;
inline void Heartbeat::clear_disk() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.disk_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t Heartbeat::disk() const {
  // @@protoc_insertion_point(field_get:heartbeat.Heartbeat.disk)
  return _internal_disk();
}
inline void Heartbeat::set_disk(::int32_t value) {
  _internal_set_disk(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:heartbeat.Heartbeat.disk)
}
inline ::int32_t Heartbeat::_internal_disk() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.disk_;
}
inline void Heartbeat::_internal_set_disk(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.disk_ = value;
}

// int32 count = 3;
inline void Heartbeat::clear_count() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.count_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t Heartbeat::count() const {
  // @@protoc_insertion_point(field_get:heartbeat.Heartbeat.count)
  return _internal_count();
}
inline void Heartbeat::set_count(::int32_t value) {
  _internal_set_count(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:heartbeat.Heartbeat.count)
}
inline ::int32_t Heartbeat::_internal_count() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.count_;
}
inline void Heartbeat::_internal_set_count(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.count_ = value;
}

// .heartbeat.Heartbeat.Status status = 4;
inline void Heartbeat::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::heartbeat::Heartbeat_Status Heartbeat::status() const {
  // @@protoc_insertion_point(field_get:heartbeat.Heartbeat.status)
  return _internal_status();
}
inline void Heartbeat::set_status(::heartbeat::Heartbeat_Status value) {
  _internal_set_status(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:heartbeat.Heartbeat.status)
}
inline ::heartbeat::Heartbeat_Status Heartbeat::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::heartbeat::Heartbeat_Status>(_impl_.status_);
}
inline void Heartbeat::_internal_set_status(::heartbeat::Heartbeat_Status value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// -------------------------------------------------------------------

// ChunkMetadata

// string chunk_id = 1;
inline void ChunkMetadata::clear_chunk_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chunk_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& ChunkMetadata::chunk_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:heartbeat.ChunkMetadata.chunk_id)
  return _internal_chunk_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ChunkMetadata::set_chunk_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.chunk_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:heartbeat.ChunkMetadata.chunk_id)
}
inline ::std::string* PROTOBUF_NONNULL ChunkMetadata::mutable_chunk_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_chunk_id();
  // @@protoc_insertion_point(field_mutable:heartbeat.ChunkMetadata.chunk_id)
  return _s;
}
inline const ::std::string& ChunkMetadata::_internal_chunk_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.chunk_id_.Get();
}
inline void ChunkMetadata::_internal_set_chunk_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.chunk_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ChunkMetadata::_internal_mutable_chunk_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.chunk_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ChunkMetadata::release_chunk_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:heartbeat.ChunkMetadata.chunk_id)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.chunk_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.chunk_id_.Set("", GetArena());
  }
  return released;
}
inline void ChunkMetadata::set_allocated_chunk_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.chunk_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.chunk_id_.IsDefault()) {
    _impl_.chunk_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:heartbeat.ChunkMetadata.chunk_id)
}

// int64 size = 2;
inline void ChunkMetadata::clear_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.size_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int64_t ChunkMetadata::size() const {
  // @@protoc_insertion_point(field_get:heartbeat.ChunkMetadata.size)
  return _internal_size();
}
inline void ChunkMetadata::set_size(::int64_t value) {
  _internal_set_size(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:heartbeat.ChunkMetadata.size)
}
inline ::int64_t ChunkMetadata::_internal_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.size_;
}
inline void ChunkMetadata::_internal_set_size(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.size_ = value;
}

// string hash = 3;
inline void ChunkMetadata::clear_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hash_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& ChunkMetadata::hash() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:heartbeat.ChunkMetadata.hash)
  return _internal_hash();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ChunkMetadata::set_hash(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.hash_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:heartbeat.ChunkMetadata.hash)
}
inline ::std::string* PROTOBUF_NONNULL ChunkMetadata::mutable_hash()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_hash();
  // @@protoc_insertion_point(field_mutable:heartbeat.ChunkMetadata.hash)
  return _s;
}
inline const ::std::string& ChunkMetadata::_internal_hash() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.hash_.Get();
}
inline void ChunkMetadata::_internal_set_hash(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.hash_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ChunkMetadata::_internal_mutable_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.hash_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ChunkMetadata::release_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:heartbeat.ChunkMetadata.hash)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.hash_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.hash_.Set("", GetArena());
  }
  return released;
}
inline void ChunkMetadata::set_allocated_hash(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.hash_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.hash_.IsDefault()) {
    _impl_.hash_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:heartbeat.ChunkMetadata.hash)
}

// repeated string replica_servers = 4;
inline int ChunkMetadata::_internal_replica_servers_size() const {
  return _internal_replica_servers().size();
}
inline int ChunkMetadata::replica_servers_size() const {
  return _internal_replica_servers_size();
}
inline void ChunkMetadata::clear_replica_servers() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.replica_servers_.Clear();
}
inline ::std::string* PROTOBUF_NONNULL ChunkMetadata::add_replica_servers()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s = _internal_mutable_replica_servers()->Add();
  // @@protoc_insertion_point(field_add_mutable:heartbeat.ChunkMetadata.replica_servers)
  return _s;
}
inline const ::std::string& ChunkMetadata::replica_servers(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:heartbeat.ChunkMetadata.replica_servers)
  return _internal_replica_servers().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL ChunkMetadata::mutable_replica_servers(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:heartbeat.ChunkMetadata.replica_servers)
  return _internal_mutable_replica_servers()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void ChunkMetadata::set_replica_servers(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_replica_servers()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:heartbeat.ChunkMetadata.replica_servers)
}
template <typename Arg_, typename... Args_>
inline void ChunkMetadata::add_replica_servers(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_replica_servers(),
                               ::std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:heartbeat.ChunkMetadata.replica_servers)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& ChunkMetadata::replica_servers()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:heartbeat.ChunkMetadata.replica_servers)
  return _internal_replica_servers();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
ChunkMetadata::mutable_replica_servers() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:heartbeat.ChunkMetadata.replica_servers)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_replica_servers();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
ChunkMetadata::_internal_replica_servers() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.replica_servers_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
ChunkMetadata::_internal_mutable_replica_servers() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.replica_servers_;
}

// -------------------------------------------------------------------

// FileChunk

// string chunk_id = 1;
inline void FileChunk::clear_chunk_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chunk_id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& FileChunk::chunk_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:heartbeat.FileChunk.chunk_id)
  return _internal_chunk_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileChunk::set_chunk_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.chunk_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:heartbeat.FileChunk.chunk_id)
}
inline ::std::string* PROTOBUF_NONNULL FileChunk::mutable_chunk_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_chunk_id();
  // @@protoc_insertion_point(field_mutable:heartbeat.FileChunk.chunk_id)
  return _s;
}
inline const ::std::string& FileChunk::_internal_chunk_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.chunk_id_.Get();
}
inline void FileChunk::_internal_set_chunk_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.chunk_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileChunk::_internal_mutable_chunk_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.chunk_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileChunk::release_chunk_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:heartbeat.FileChunk.chunk_id)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.chunk_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.chunk_id_.Set("", GetArena());
  }
  return released;
}
inline void FileChunk::set_allocated_chunk_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.chunk_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.chunk_id_.IsDefault()) {
    _impl_.chunk_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:heartbeat.FileChunk.chunk_id)
}

// bytes data = 2;
inline void FileChunk::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& FileChunk::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:heartbeat.FileChunk.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileChunk::set_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:heartbeat.FileChunk.data)
}
inline ::std::string* PROTOBUF_NONNULL FileChunk::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:heartbeat.FileChunk.data)
  return _s;
}
inline const ::std::string& FileChunk::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void FileChunk::_internal_set_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileChunk::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileChunk::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:heartbeat.FileChunk.data)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.data_.Set("", GetArena());
  }
  return released;
}
inline void FileChunk::set_allocated_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:heartbeat.FileChunk.data)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace heartbeat


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::heartbeat::Heartbeat_Status> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::heartbeat::Heartbeat_Status>() {
  return ::heartbeat::Heartbeat_Status_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // heat_5fbeat_2eproto_2epb_2eh
