// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: heat_beat.proto
// Protobuf C++ Version: 6.31.1

#include "heat_beat.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace heartbeat {

inline constexpr Heartbeat::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        cpu_{0},
        disk_{0},
        count_{0},
        status_{static_cast< ::heartbeat::Heartbeat_Status >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR Heartbeat::Heartbeat(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Heartbeat_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct HeartbeatDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartbeatDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartbeatDefaultTypeInternal() {}
  union {
    Heartbeat _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartbeatDefaultTypeInternal _Heartbeat_default_instance_;

inline constexpr FileChunk::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        chunk_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR FileChunk::FileChunk(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(FileChunk_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FileChunkDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileChunkDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileChunkDefaultTypeInternal() {}
  union {
    FileChunk _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileChunkDefaultTypeInternal _FileChunk_default_instance_;

inline constexpr ChunkMetadata::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        replica_servers_{},
        chunk_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        hash_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        size_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR ChunkMetadata::ChunkMetadata(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ChunkMetadata_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ChunkMetadataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ChunkMetadataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ChunkMetadataDefaultTypeInternal() {}
  union {
    ChunkMetadata _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ChunkMetadataDefaultTypeInternal _ChunkMetadata_default_instance_;
}  // namespace heartbeat
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_heat_5fbeat_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_heat_5fbeat_2eproto = nullptr;
const ::uint32_t
    TableStruct_heat_5fbeat_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::heartbeat::Heartbeat, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::heartbeat::Heartbeat, _impl_.cpu_),
        PROTOBUF_FIELD_OFFSET(::heartbeat::Heartbeat, _impl_.disk_),
        PROTOBUF_FIELD_OFFSET(::heartbeat::Heartbeat, _impl_.count_),
        PROTOBUF_FIELD_OFFSET(::heartbeat::Heartbeat, _impl_.status_),
        0,
        1,
        2,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::heartbeat::ChunkMetadata, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::heartbeat::ChunkMetadata, _impl_.chunk_id_),
        PROTOBUF_FIELD_OFFSET(::heartbeat::ChunkMetadata, _impl_.size_),
        PROTOBUF_FIELD_OFFSET(::heartbeat::ChunkMetadata, _impl_.hash_),
        PROTOBUF_FIELD_OFFSET(::heartbeat::ChunkMetadata, _impl_.replica_servers_),
        0,
        2,
        1,
        ~0u,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::heartbeat::FileChunk, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::heartbeat::FileChunk, _impl_.chunk_id_),
        PROTOBUF_FIELD_OFFSET(::heartbeat::FileChunk, _impl_.data_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::heartbeat::Heartbeat)},
        {11, sizeof(::heartbeat::ChunkMetadata)},
        {22, sizeof(::heartbeat::FileChunk)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::heartbeat::_Heartbeat_default_instance_._instance,
    &::heartbeat::_ChunkMetadata_default_instance_._instance,
    &::heartbeat::_FileChunk_default_instance_._instance,
};
const char descriptor_table_protodef_heat_5fbeat_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017heat_beat.proto\022\theartbeat\"\216\001\n\tHeartbe"
    "at\022\013\n\003cpu\030\001 \001(\005\022\014\n\004disk\030\002 \001(\005\022\r\n\005count\030\003"
    " \001(\005\022+\n\006status\030\004 \001(\0162\033.heartbeat.Heartbe"
    "at.Status\"*\n\006Status\022\013\n\007UNKNOWN\020\000\022\t\n\005ALIV"
    "E\020\001\022\010\n\004DEAD\020\002\"V\n\rChunkMetadata\022\020\n\010chunk_"
    "id\030\001 \001(\t\022\014\n\004size\030\002 \001(\003\022\014\n\004hash\030\003 \001(\t\022\027\n\017"
    "replica_servers\030\004 \003(\t\"+\n\tFileChunk\022\020\n\010ch"
    "unk_id\030\001 \001(\t\022\014\n\004data\030\002 \001(\014b\006proto3"
};
static ::absl::once_flag descriptor_table_heat_5fbeat_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_heat_5fbeat_2eproto = {
    false,
    false,
    314,
    descriptor_table_protodef_heat_5fbeat_2eproto,
    "heat_beat.proto",
    &descriptor_table_heat_5fbeat_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_heat_5fbeat_2eproto::offsets,
    file_level_enum_descriptors_heat_5fbeat_2eproto,
    file_level_service_descriptors_heat_5fbeat_2eproto,
};
namespace heartbeat {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Heartbeat_Status_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_heat_5fbeat_2eproto);
  return file_level_enum_descriptors_heat_5fbeat_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Heartbeat_Status_internal_data_[] = {
    196608u, 0u, };
// ===================================================================

class Heartbeat::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Heartbeat>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_._has_bits_);
};

Heartbeat::Heartbeat(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Heartbeat_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:heartbeat.Heartbeat)
}
Heartbeat::Heartbeat(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Heartbeat& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Heartbeat_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE Heartbeat::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Heartbeat::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, cpu_),
           0,
           offsetof(Impl_, status_) -
               offsetof(Impl_, cpu_) +
               sizeof(Impl_::status_));
}
Heartbeat::~Heartbeat() {
  // @@protoc_insertion_point(destructor:heartbeat.Heartbeat)
  SharedDtor(*this);
}
inline void Heartbeat::SharedDtor(MessageLite& self) {
  Heartbeat& this_ = static_cast<Heartbeat&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Heartbeat::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Heartbeat(arena);
}
constexpr auto Heartbeat::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Heartbeat),
                                            alignof(Heartbeat));
}
constexpr auto Heartbeat::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Heartbeat_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Heartbeat::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Heartbeat>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Heartbeat::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Heartbeat>(), &Heartbeat::ByteSizeLong,
              &Heartbeat::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_._cached_size_),
          false,
      },
      &Heartbeat::kDescriptorMethods,
      &descriptor_table_heat_5fbeat_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Heartbeat_class_data_ =
        Heartbeat::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Heartbeat::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Heartbeat_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Heartbeat_class_data_.tc_table);
  return Heartbeat_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2>
Heartbeat::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Heartbeat_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::heartbeat::Heartbeat>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .heartbeat.Heartbeat.Status status = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Heartbeat, _impl_.status_), 3>(),
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_.status_)}},
    // int32 cpu = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Heartbeat, _impl_.cpu_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_.cpu_)}},
    // int32 disk = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Heartbeat, _impl_.disk_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_.disk_)}},
    // int32 count = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Heartbeat, _impl_.count_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_.count_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 cpu = 1;
    {PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_.cpu_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 disk = 2;
    {PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_.disk_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 count = 3;
    {PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_.count_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // .heartbeat.Heartbeat.Status status = 4;
    {PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_.status_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Heartbeat::Clear() {
// @@protoc_insertion_point(message_clear_start:heartbeat.Heartbeat)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    ::memset(&_impl_.cpu_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.status_) -
        reinterpret_cast<char*>(&_impl_.cpu_)) + sizeof(_impl_.status_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Heartbeat::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Heartbeat& this_ = static_cast<const Heartbeat&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Heartbeat::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Heartbeat& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:heartbeat.Heartbeat)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 cpu = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_cpu() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_cpu(), target);
    }
  }

  // int32 disk = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_disk() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_disk(), target);
    }
  }

  // int32 count = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_count() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
              stream, this_._internal_count(), target);
    }
  }

  // .heartbeat.Heartbeat.Status status = 4;
  if ((this_._impl_._has_bits_[0] & 0x00000008u) != 0) {
    if (this_._internal_status() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          4, this_._internal_status(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:heartbeat.Heartbeat)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Heartbeat::ByteSizeLong(const MessageLite& base) {
  const Heartbeat& this_ = static_cast<const Heartbeat&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Heartbeat::ByteSizeLong() const {
  const Heartbeat& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:heartbeat.Heartbeat)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    // int32 cpu = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_cpu() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_cpu());
      }
    }
    // int32 disk = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_disk() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_disk());
      }
    }
    // int32 count = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_count() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_count());
      }
    }
    // .heartbeat.Heartbeat.Status status = 4;
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (this_._internal_status() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Heartbeat::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Heartbeat*>(&to_msg);
  auto& from = static_cast<const Heartbeat&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:heartbeat.Heartbeat)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (from._internal_cpu() != 0) {
        _this->_impl_.cpu_ = from._impl_.cpu_;
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_disk() != 0) {
        _this->_impl_.disk_ = from._impl_.disk_;
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_count() != 0) {
        _this->_impl_.count_ = from._impl_.count_;
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (from._internal_status() != 0) {
        _this->_impl_.status_ = from._impl_.status_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Heartbeat::CopyFrom(const Heartbeat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:heartbeat.Heartbeat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Heartbeat::InternalSwap(Heartbeat* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_.status_)
      + sizeof(Heartbeat::_impl_.status_)
      - PROTOBUF_FIELD_OFFSET(Heartbeat, _impl_.cpu_)>(
          reinterpret_cast<char*>(&_impl_.cpu_),
          reinterpret_cast<char*>(&other->_impl_.cpu_));
}

::google::protobuf::Metadata Heartbeat::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ChunkMetadata::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ChunkMetadata>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ChunkMetadata, _impl_._has_bits_);
};

ChunkMetadata::ChunkMetadata(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ChunkMetadata_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:heartbeat.ChunkMetadata)
}
PROTOBUF_NDEBUG_INLINE ChunkMetadata::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::heartbeat::ChunkMetadata& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        replica_servers_{visibility, arena, from.replica_servers_},
        chunk_id_(arena, from.chunk_id_),
        hash_(arena, from.hash_) {}

ChunkMetadata::ChunkMetadata(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ChunkMetadata& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ChunkMetadata_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ChunkMetadata* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.size_ = from._impl_.size_;

  // @@protoc_insertion_point(copy_constructor:heartbeat.ChunkMetadata)
}
PROTOBUF_NDEBUG_INLINE ChunkMetadata::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        replica_servers_{visibility, arena},
        chunk_id_(arena),
        hash_(arena) {}

inline void ChunkMetadata::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.size_ = {};
}
ChunkMetadata::~ChunkMetadata() {
  // @@protoc_insertion_point(destructor:heartbeat.ChunkMetadata)
  SharedDtor(*this);
}
inline void ChunkMetadata::SharedDtor(MessageLite& self) {
  ChunkMetadata& this_ = static_cast<ChunkMetadata&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.chunk_id_.Destroy();
  this_._impl_.hash_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ChunkMetadata::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ChunkMetadata(arena);
}
constexpr auto ChunkMetadata::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ChunkMetadata, _impl_.replica_servers_) +
          decltype(ChunkMetadata::_impl_.replica_servers_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(ChunkMetadata), alignof(ChunkMetadata), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ChunkMetadata::PlacementNew_,
                                 sizeof(ChunkMetadata),
                                 alignof(ChunkMetadata));
  }
}
constexpr auto ChunkMetadata::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ChunkMetadata_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ChunkMetadata::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ChunkMetadata>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ChunkMetadata::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ChunkMetadata>(), &ChunkMetadata::ByteSizeLong,
              &ChunkMetadata::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ChunkMetadata, _impl_._cached_size_),
          false,
      },
      &ChunkMetadata::kDescriptorMethods,
      &descriptor_table_heat_5fbeat_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ChunkMetadata_class_data_ =
        ChunkMetadata::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ChunkMetadata::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ChunkMetadata_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ChunkMetadata_class_data_.tc_table);
  return ChunkMetadata_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 59, 2>
ChunkMetadata::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ChunkMetadata, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ChunkMetadata_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::heartbeat::ChunkMetadata>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated string replica_servers = 4;
    {::_pbi::TcParser::FastUR1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(ChunkMetadata, _impl_.replica_servers_)}},
    // string chunk_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(ChunkMetadata, _impl_.chunk_id_)}},
    // int64 size = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ChunkMetadata, _impl_.size_), 2>(),
     {16, 2, 0, PROTOBUF_FIELD_OFFSET(ChunkMetadata, _impl_.size_)}},
    // string hash = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0, PROTOBUF_FIELD_OFFSET(ChunkMetadata, _impl_.hash_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string chunk_id = 1;
    {PROTOBUF_FIELD_OFFSET(ChunkMetadata, _impl_.chunk_id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 size = 2;
    {PROTOBUF_FIELD_OFFSET(ChunkMetadata, _impl_.size_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // string hash = 3;
    {PROTOBUF_FIELD_OFFSET(ChunkMetadata, _impl_.hash_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated string replica_servers = 4;
    {PROTOBUF_FIELD_OFFSET(ChunkMetadata, _impl_.replica_servers_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
  }},
  // no aux_entries
  {{
    "\27\10\0\4\17\0\0\0"
    "heartbeat.ChunkMetadata"
    "chunk_id"
    "hash"
    "replica_servers"
  }},
};
PROTOBUF_NOINLINE void ChunkMetadata::Clear() {
// @@protoc_insertion_point(message_clear_start:heartbeat.ChunkMetadata)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.replica_servers_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.chunk_id_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.hash_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.size_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ChunkMetadata::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ChunkMetadata& this_ = static_cast<const ChunkMetadata&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ChunkMetadata::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ChunkMetadata& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:heartbeat.ChunkMetadata)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string chunk_id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_chunk_id().empty()) {
      const ::std::string& _s = this_._internal_chunk_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "heartbeat.ChunkMetadata.chunk_id");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // int64 size = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_size() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_size(), target);
    }
  }

  // string hash = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._internal_hash().empty()) {
      const ::std::string& _s = this_._internal_hash();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "heartbeat.ChunkMetadata.hash");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // repeated string replica_servers = 4;
  for (int i = 0, n = this_._internal_replica_servers_size(); i < n; ++i) {
    const auto& s = this_._internal_replica_servers().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "heartbeat.ChunkMetadata.replica_servers");
    target = stream->WriteString(4, s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:heartbeat.ChunkMetadata)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ChunkMetadata::ByteSizeLong(const MessageLite& base) {
  const ChunkMetadata& this_ = static_cast<const ChunkMetadata&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ChunkMetadata::ByteSizeLong() const {
  const ChunkMetadata& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:heartbeat.ChunkMetadata)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated string replica_servers = 4;
    {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_replica_servers().size());
      for (int i = 0, n = this_._internal_replica_servers().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_replica_servers().Get(i));
      }
    }
  }
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // string chunk_id = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_chunk_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_chunk_id());
      }
    }
    // string hash = 3;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_hash().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_hash());
      }
    }
    // int64 size = 2;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_size() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_size());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ChunkMetadata::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ChunkMetadata*>(&to_msg);
  auto& from = static_cast<const ChunkMetadata&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:heartbeat.ChunkMetadata)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_replica_servers()->MergeFrom(from._internal_replica_servers());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_chunk_id().empty()) {
        _this->_internal_set_chunk_id(from._internal_chunk_id());
      } else {
        if (_this->_impl_.chunk_id_.IsDefault()) {
          _this->_internal_set_chunk_id("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_hash().empty()) {
        _this->_internal_set_hash(from._internal_hash());
      } else {
        if (_this->_impl_.hash_.IsDefault()) {
          _this->_internal_set_hash("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_size() != 0) {
        _this->_impl_.size_ = from._impl_.size_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ChunkMetadata::CopyFrom(const ChunkMetadata& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:heartbeat.ChunkMetadata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ChunkMetadata::InternalSwap(ChunkMetadata* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.replica_servers_.InternalSwap(&other->_impl_.replica_servers_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.chunk_id_, &other->_impl_.chunk_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.hash_, &other->_impl_.hash_, arena);
  swap(_impl_.size_, other->_impl_.size_);
}

::google::protobuf::Metadata ChunkMetadata::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class FileChunk::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<FileChunk>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(FileChunk, _impl_._has_bits_);
};

FileChunk::FileChunk(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FileChunk_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:heartbeat.FileChunk)
}
PROTOBUF_NDEBUG_INLINE FileChunk::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::heartbeat::FileChunk& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        chunk_id_(arena, from.chunk_id_),
        data_(arena, from.data_) {}

FileChunk::FileChunk(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const FileChunk& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FileChunk_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  FileChunk* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:heartbeat.FileChunk)
}
PROTOBUF_NDEBUG_INLINE FileChunk::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        chunk_id_(arena),
        data_(arena) {}

inline void FileChunk::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
FileChunk::~FileChunk() {
  // @@protoc_insertion_point(destructor:heartbeat.FileChunk)
  SharedDtor(*this);
}
inline void FileChunk::SharedDtor(MessageLite& self) {
  FileChunk& this_ = static_cast<FileChunk&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.chunk_id_.Destroy();
  this_._impl_.data_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL FileChunk::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) FileChunk(arena);
}
constexpr auto FileChunk::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(FileChunk),
                                            alignof(FileChunk));
}
constexpr auto FileChunk::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_FileChunk_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &FileChunk::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<FileChunk>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &FileChunk::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<FileChunk>(), &FileChunk::ByteSizeLong,
              &FileChunk::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(FileChunk, _impl_._cached_size_),
          false,
      },
      &FileChunk::kDescriptorMethods,
      &descriptor_table_heat_5fbeat_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull FileChunk_class_data_ =
        FileChunk::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
FileChunk::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&FileChunk_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(FileChunk_class_data_.tc_table);
  return FileChunk_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 36, 2>
FileChunk::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(FileChunk, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    FileChunk_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::heartbeat::FileChunk>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes data = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.data_)}},
    // string chunk_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.chunk_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string chunk_id = 1;
    {PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.chunk_id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes data = 2;
    {PROTOBUF_FIELD_OFFSET(FileChunk, _impl_.data_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\10\0\0\0\0\0\0"
    "heartbeat.FileChunk"
    "chunk_id"
  }},
};
PROTOBUF_NOINLINE void FileChunk::Clear() {
// @@protoc_insertion_point(message_clear_start:heartbeat.FileChunk)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.chunk_id_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.data_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL FileChunk::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const FileChunk& this_ = static_cast<const FileChunk&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL FileChunk::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const FileChunk& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:heartbeat.FileChunk)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string chunk_id = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_chunk_id().empty()) {
      const ::std::string& _s = this_._internal_chunk_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "heartbeat.FileChunk.chunk_id");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // bytes data = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._internal_data().empty()) {
      const ::std::string& _s = this_._internal_data();
      target = stream->WriteBytesMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:heartbeat.FileChunk)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t FileChunk::ByteSizeLong(const MessageLite& base) {
  const FileChunk& this_ = static_cast<const FileChunk&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t FileChunk::ByteSizeLong() const {
  const FileChunk& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:heartbeat.FileChunk)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // string chunk_id = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_chunk_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_chunk_id());
      }
    }
    // bytes data = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_data().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_data());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void FileChunk::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<FileChunk*>(&to_msg);
  auto& from = static_cast<const FileChunk&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:heartbeat.FileChunk)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_chunk_id().empty()) {
        _this->_internal_set_chunk_id(from._internal_chunk_id());
      } else {
        if (_this->_impl_.chunk_id_.IsDefault()) {
          _this->_internal_set_chunk_id("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_data().empty()) {
        _this->_internal_set_data(from._internal_data());
      } else {
        if (_this->_impl_.data_.IsDefault()) {
          _this->_internal_set_data("");
        }
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileChunk::CopyFrom(const FileChunk& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:heartbeat.FileChunk)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FileChunk::InternalSwap(FileChunk* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.chunk_id_, &other->_impl_.chunk_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
}

::google::protobuf::Metadata FileChunk::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace heartbeat
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_heat_5fbeat_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
